FROM golang:1.24-alpine AS builder
WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod tidy
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /usr/src/app/main .
EXPOSE 8000
CMD ["./main"]